INSERT INTO permissions (key, category, label) VALUES
('org.settings.manage', 'org', 'Manage organization settings and branding'),
('org.billing.manage', 'org', 'Manage billing and subscription'),
('org.billing.view', 'org', 'View billing and invoices'),
('role.manage', 'org', 'Create, edit, and delete roles'),
('role.assign', 'org', 'Assign roles to users'),
('user.invite', 'org', 'Invite new users to organization'),
('user.remove', 'org', 'Remove users from organization'),
('audit_log.view', 'org', 'View audit log'),
('project.create', 'project', 'Create new projects'),
('project.view_all', 'project', 'View all projects org-wide'),
('project.view_assigned', 'project', 'View only assigned projects'),
('project.edit', 'project', 'Edit project details'),
('project.archive', 'project', 'Archive or delete projects'),
('project.view_progress', 'project', 'View project progress and rollup dashboards'),
('sprint.create', 'sprint', 'Create sprints within a project'),
('sprint.edit', 'sprint', 'Edit sprint details'),
('sprint.close', 'sprint', 'Close or complete a sprint'),
('sprint.view', 'sprint', 'View sprint boards and burndown'),
('sprint.assign_task', 'sprint', 'Move tasks into or out of a sprint'),
('task.create', 'task', 'Create tasks within a project'),
('task.assign', 'task', 'Assign tasks to users'),
('task.reassign', 'task', 'Reassign tasks between users'),
('task.view_all', 'task', 'View all tasks in a project'),
('task.view_assigned', 'task', 'View only tasks assigned to self'),
('task.update_status', 'task', 'Update task status or progress'),
('task.edit', 'task', 'Edit task details'),
('task.delete', 'task', 'Delete tasks'),
('task.comment', 'task', 'Comment on tasks'),
('agent.trigger', 'agent', 'Manually trigger an AI agent action'),
('agent.autonomous_run', 'agent', 'Allow agent to act automatically without approval'),
('agent.view_log', 'agent', 'View AI agent action history'),
('agent.revert', 'agent', 'Undo or revert an AI agent action'),
('report.view', 'report', 'View reports and analytics'),
('report.export', 'report', 'Export reports as CSV or PDF');